#pragma once

#include "Core/Defines.h"

DEFINE_JS_TRACE_TYPE(Asset);

DEFINE_JS_TRACE_TYPE(Config);

DEFINE_JS_TRACE_TYPE(Core);
DEFINE_JS_TRACE_TYPE(Module);

DEFINE_JS_TRACE_TYPE(Editor);

DEFINE_JS_TRACE_TYPE(Entity);

DEFINE_JS_TRACE_TYPE(Input);

DEFINE_JS_TRACE_TYPE(Math);

DEFINE_JS_TRACE_TYPE(Platform);

DEFINE_JS_TRACE_TYPE(Property);
DEFINE_JS_TRACE_TYPE(PropertyExtended);

DEFINE_JS_TRACE_TYPE(Rendering);
